/* Copyright (C) 2022-2026 Free Software Foundation, Inc.

   Author: Gregory John Casamento <greg.casamento@gmail.com>

   This file is part of GNUstep.
*/

#ifndef _AVFoundation_h_GNUSTEP_INCLUDE
#define _AVFoundation_h_GNUSTEP_INCLUDE

#import <AVFoundation/AVTime.h>
#import <AVFoundation/AVMediaFormat.h>
#import <AVFoundation/AVAsset.h>
#import <AVFoundation/AVURLAsset.h>
#import <AVFoundation/AVAssetTrack.h>
#import <AVFoundation/AVMetadataItem.h>
#import <AVFoundation/AVPlayerItem.h>
#import <AVFoundation/AVPlayer.h>
#import <AVFoundation/AVAudioPlayer.h>
#import <AVFoundation/AVAudioTypes.h>
#import <AVFoundation/AVAudioFormat.h>
#import <AVFoundation/AVAudioPCMBuffer.h>
#import <AVFoundation/AVAudioFile.h>
#import <AVFoundation/AVAudioEngine.h>
#import <AVFoundation/AVAudioUnit.h>
#import <AVFoundation/AVMIDIPlayer.h>
#import <AVFoundation/AVAggregateAssetDownloadTask.h>
#import <AVFoundation/AVAssetCache.h>
#import <AVFoundation/AVAssetDownloadConfiguration.h>
#import <AVFoundation/AVAssetDownloadTask.h>
#import <AVFoundation/AVAssetDownloadURLSession.h>
#import <AVFoundation/AVAssetExportSession.h>
#import <AVFoundation/AVAssetImageGenerator.h>
#import <AVFoundation/AVAssetPlaybackAssistant.h>
#import <AVFoundation/AVAssetReader.h>
#import <AVFoundation/AVAssetReaderAudioMixOutput.h>
#import <AVFoundation/AVAssetReaderOutput.h>
#import <AVFoundation/AVAssetReaderOutputMetadataAdaptor.h>
#import <AVFoundation/AVAssetReaderSampleReferenceOutput.h>
#import <AVFoundation/AVAssetReaderTrackOutput.h>
#import <AVFoundation/AVAssetReaderVideoCompositionOutput.h>
#import <AVFoundation/AVAssetTrackGroup.h>
#import <AVFoundation/AVAssetTrackSegment.h>
#import <AVFoundation/AVAssetWriter.h>
#import <AVFoundation/AVAssetWriterInput.h>
#import <AVFoundation/AVAssetWriterInputGroup.h>
#import <AVFoundation/AVAssetWriterInputMetadataAdaptor.h>
#import <AVFoundation/AVAssetWriterInputPassDescription.h>
#import <AVFoundation/AVAssetWriterInputPixelBufferAdaptor.h>
#import <AVFoundation/AVAssetWriterInputTaggedPixelBufferGroupAdaptor.h>
#import <AVFoundation/AVAsynchronousCIImageFilteringRequest.h>
#import <AVFoundation/AVAudioApplication.h>
#import <AVFoundation/AVAudioMix.h>
#import <AVFoundation/AVAudioMixInputParameters.h>
#import <AVFoundation/AVAudioRecorder.h>
#import <AVFoundation/AVAudioRoutingArbiter.h>
#import <AVFoundation/AVAudioSession.h>
#import <AVFoundation/AVCameraCalibrationData.h>
#import <AVFoundation/AVCaptureAudioDataOutput.h>
#import <AVFoundation/AVCaptureAudioFileOutput.h>
#import <AVFoundation/AVCaptureAudioPreviewOutput.h>
#import <AVFoundation/AVCaptureAutoExposureBracketedStillImageSettings.h>
#import <AVFoundation/AVCaptureBracketedStillImageSettings.h>
#import <AVFoundation/AVCaptureConnection.h>
#import <AVFoundation/AVCaptureControl.h>
#import <AVFoundation/AVCaptureDataOutputSynchronizer.h>
#import <AVFoundation/AVCaptureDeferredPhotoProxy.h>
#import <AVFoundation/AVCaptureDepthDataOutput.h>
#import <AVFoundation/AVCaptureDevice.h>
#import <AVFoundation/AVCaptureDeviceDiscoverySession.h>
#import <AVFoundation/AVCaptureDeviceFormat.h>
#import <AVFoundation/AVCaptureDeviceInput.h>
#import <AVFoundation/AVCaptureExternalDisplayConfiguration.h>
#import <AVFoundation/AVCaptureExternalDisplayConfigurator.h>
#import <AVFoundation/AVCaptureFileOutput.h>
#import <AVFoundation/AVCaptureIndexPicker.h>
#import <AVFoundation/AVCaptureInput.h>
#import <AVFoundation/AVCaptureInputPort.h>
#import <AVFoundation/AVCaptureManualExposureBracketedStillImageSettings.h>
#import <AVFoundation/AVCaptureMetadataOutput.h>
#import <AVFoundation/AVCaptureMovieFileOutput.h>
#import <AVFoundation/AVCaptureMultiCamSession.h>
#import <AVFoundation/AVCaptureOutput.h>
#import <AVFoundation/AVCapturePhoto.h>
#import <AVFoundation/AVCapturePhotoOutput.h>
#import <AVFoundation/AVCapturePhotoOutputReadinessCoordinator.h>
#import <AVFoundation/AVCapturePhotoSettings.h>
#import <AVFoundation/AVCaptureResolvedPhotoSettings.h>
#import <AVFoundation/AVCaptureScreenInput.h>
#import <AVFoundation/AVCaptureSession.h>
#import <AVFoundation/AVCaptureSlider.h>
#import <AVFoundation/AVCaptureSpatialAudioMetadataSampleGenerator.h>
#import <AVFoundation/AVCaptureStillImageOutput.h>
#import <AVFoundation/AVCaptureSynchronizedData.h>
#import <AVFoundation/AVCaptureSynchronizedDepthData.h>
#import <AVFoundation/AVCaptureSynchronizedMetadataObjectData.h>
#import <AVFoundation/AVCaptureSynchronizedSampleBufferData.h>
#import <AVFoundation/AVCaptureSystemExposureBiasSlider.h>
#import <AVFoundation/AVCaptureSystemZoomSlider.h>
#import <AVFoundation/AVCaptureTimecodeGenerator.h>
#import <AVFoundation/AVCaptureVideoDataOutput.h>
#import <AVFoundation/AVCaptureVideoPreviewLayer.h>
#import <AVFoundation/AVComposition.h>
#import <AVFoundation/AVCompositionTrack.h>
#import <AVFoundation/AVCompositionTrackSegment.h>
#import <AVFoundation/AVContentKeyReportGroup.h>
#import <AVFoundation/AVContentKeyRequest.h>
#import <AVFoundation/AVContentKeyResponse.h>
#import <AVFoundation/AVContentKeySession.h>
#import <AVFoundation/AVContentKeySpecifier.h>
#import <AVFoundation/AVContinuityDevice.h>
#import <AVFoundation/AVDelegatingPlaybackCoordinator.h>
#import <AVFoundation/AVDepthData.h>
#import <AVFoundation/AVExternalStorageDevice.h>
#import <AVFoundation/AVExternalStorageDeviceDiscoverySession.h>
#import <AVFoundation/AVExternalSyncDevice.h>
#import <AVFoundation/AVFragmentedAsset.h>
#import <AVFoundation/AVFragmentedAssetMinder.h>
#import <AVFoundation/AVFragmentedAssetTrack.h>
#import <AVFoundation/AVFragmentedMovie.h>
#import <AVFoundation/AVFragmentedMovieMinder.h>
#import <AVFoundation/AVFragmentedMovieTrack.h>
#import <AVFoundation/AVMediaDataStorage.h>
#import <AVFoundation/AVMediaSelection.h>
#import <AVFoundation/AVMediaSelectionGroup.h>
#import <AVFoundation/AVMediaSelectionOption.h>
#import <AVFoundation/AVMetadataItemFilter.h>
#import <AVFoundation/AVMetadataObject.h>
#import <AVFoundation/AVMetadataBodyObject.h>
#import <AVFoundation/AVMetadataCatBodyObject.h>
#import <AVFoundation/AVMetadataDogBodyObject.h>
#import <AVFoundation/AVMetadataFaceObject.h>
#import <AVFoundation/AVMetadataHumanBodyObject.h>
#import <AVFoundation/AVMetadataMachineReadableCodeObject.h>
#import <AVFoundation/AVMetadataSalientObject.h>
#import <AVFoundation/AVMovie.h>
#import <AVFoundation/AVMovieTrack.h>
#import <AVFoundation/AVMutableAudioMix.h>
#import <AVFoundation/AVMutableAudioMixInputParameters.h>
#import <AVFoundation/AVMutableComposition.h>
#import <AVFoundation/AVMutableCompositionTrack.h>
#import <AVFoundation/AVMutableMetadataItem.h>
#import <AVFoundation/AVMutableMovie.h>
#import <AVFoundation/AVMutableMovieTrack.h>
#import <AVFoundation/AVMutableVideoComposition.h>
#import <AVFoundation/AVMutableVideoCompositionInstruction.h>
#import <AVFoundation/AVMutableVideoCompositionLayerInstruction.h>
#import <AVFoundation/AVOutputSettingsAssistant.h>
#import <AVFoundation/AVPersistableContentKeyRequest.h>
#import <AVFoundation/AVPlaybackCoordinationMedium.h>
#import <AVFoundation/AVPlaybackCoordinator.h>
#import <AVFoundation/AVPlayerItemLegibleOutput.h>
#import <AVFoundation/AVPlayerItemMetadataCollector.h>
#import <AVFoundation/AVPlayerItemMetadataOutput.h>
#import <AVFoundation/AVPlayerItemOutput.h>
#import <AVFoundation/AVPlayerItemRenderedLegibleOutput.h>
#import <AVFoundation/AVPlayerItemSampleBufferOutput.h>
#import <AVFoundation/AVPlayerItemTrack.h>
#import <AVFoundation/AVPlayerItemVideoOutput.h>
#import <AVFoundation/AVPlayerLayer.h>
#import <AVFoundation/AVPlayerLooper.h>
#import <AVFoundation/AVPlayerPlaybackCoordinator.h>
#import <AVFoundation/AVPlayerVideoOutput.h>
#import <AVFoundation/AVPortraitEffectsMatte.h>
#import <AVFoundation/AVQueuePlayer.h>
#import <AVFoundation/AVRenderedCaptionImage.h>
#import <AVFoundation/AVSampleBufferAudioRenderer.h>
#import <AVFoundation/AVSampleBufferDisplayLayer.h>
#import <AVFoundation/AVSampleBufferGenerator.h>
#import <AVFoundation/AVSampleBufferGeneratorBatch.h>
#import <AVFoundation/AVSampleBufferRenderSynchronizer.h>
#import <AVFoundation/AVSampleBufferRequest.h>
#import <AVFoundation/AVSampleBufferVideoRenderer.h>
#import <AVFoundation/AVSemanticSegmentationMatte.h>
#import <AVFoundation/AVSpeechSynthesisProviderAudioUnit.h>
#import <AVFoundation/AVSpeechSynthesisVoice.h>
#import <AVFoundation/AVSpeechSynthesizer.h>
#import <AVFoundation/AVSpeechUtterance.h>
#import <AVFoundation/AVSynchronizedLayer.h>
#import <AVFoundation/AVTimedMetadataGroup.h>
#import <AVFoundation/AVVideoComposition.h>
#import <AVFoundation/AVVideoCompositionCoreAnimationTool.h>
#import <AVFoundation/AVVideoCompositionInstruction.h>
#import <AVFoundation/AVVideoCompositionLayerInstruction.h>
#import <AVFoundation/AVVideoOutputSpecification.h>
#import <AVFoundation/AVMutableTimedMetadataGroup.h>

#endif
